# ================= 7) .github/workflows/terraform.yml =================
# Dev-only workflow WITHOUT PRs. Runs a Plan on push to main, shows it in the
# job summary, and waits for manual approval (Environment "dev") before Apply.
# Uses AWS OIDC; caches providers. You can also trigger manually via
# "Run workflow" (workflow_dispatch).
#
# Setup once in GitHub:
# 1) Settings → Actions → Variables: set AWS_REGION (e.g., us-east-1)
# 2) Settings → Actions → Variables or Secrets: set AWS_ROLE_ARN to your OIDC role ARN
# 3) Settings → Environments → New environment "dev" → Required reviewers (you)
# 4) Ensure envs/dev/terraform.tfvars exists in the repo

name: Terraform (dev)

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - 'envs/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  TF_IN_AUTOMATION: 'true'
  TF_INPUT: 'false'
  TF_CLI_ARGS: '-no-color'
  TF_PLUGIN_CACHE_DIR: .terraform/plugin-cache

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt_validate:
    name: Format & Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Terraform version
        run: terraform version

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: .terraform/plugin-cache
          key: ${{ runner.os }}-tf-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Init (no backend)
        run: terraform init -backend=false

      - name: terraform fmt & validate
        run: |
          terraform fmt -check -recursive
          terraform validate

  plan_dev:
    name: Plan (dev) on push
    needs: fmt_validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN || secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: .terraform/plugin-cache
          key: ${{ runner.os }}-tf-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Check dev var-file exists
        run: |
          test -f "envs/dev/terraform.tfvars" || { echo "Missing envs/dev/terraform.tfvars"; exit 1; }

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan (dev)
        run: terraform plan -lock-timeout=2m -var-file="envs/dev/terraform.tfvars" -out=tfplan

      - name: Render plan to file
        run: terraform show -no-color tfplan > plan.txt

      - name: Summarize plan in job summary
        run: |
          echo '### Terraform Plan (dev)' >> $GITHUB_STEP_SUMMARY
          sed -n '1,400p' plan.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload Plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: tfplan

  apply_dev:
    name: Apply (dev) — requires approval
    needs: plan_dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN || secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: .terraform/plugin-cache
          key: ${{ runner.os }}-tf-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Download Plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-dev
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
